spring:
  redis:
    host: 192.168.1.31
    password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/data1?serverTimezone=UTC
    username: root
    password: 1105lwc
    driverClassName: com.mysql.cj.jdbc.Driver